### ISSUE TITLE
Exit status should be non zero if an assertion failed

### ISSUE THREAD

**Issue by errm** [nassersala/cbdd#1]
Using the example in the README:

```
$ clang test.c -lcbdd
$ ./a.out
c strings
- is a null terminated array of char's
- has a syntactic sugar
FAILED
expected: 82
got: 105
test.c:16
$ echo $?
0
```

**Comment by nassersala** [comment]
Hi errm,
Falling in this context is success since 'failing' was expected. It would've indicated a problem with the lib itself had it returned 1.

**Comment by errm** [comment]
I don't understand what you mean... it the testsuite is failing  surely the output should be non zero? otherwise how can you use this on CI ?

**Comment by nassersala** [comment]
done
